Test for user service impl   confirm user registration
Simple-as-Coding/tutoring-platform pull request #128
Opened 2023-07-08 07:14 UTC by GrzegorzHolui

2023-07-08 18:00 UTC, McBlankenburg commented
![image](https://github.com/Simple-as-Coding/tutoring-platform/assets/58309339/4c9d42ad-4e14-4890-aff2-2f1d9b823e2c)
Repair this bug

2023-07-08 18:10 UTC, McBlankenburg requested changes
the application does not build, the application does not build, deficiencies in imports, encapsulation of variables needs to be improved.

2023-07-08 18:10 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +    PasswordEncoder passwordEncoder;
private

2023-07-08 18:10 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +    JavaMailSender mailSender;
private

2023-07-08 18:10 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +    UserModelMapper userModelMapper;
private

2023-07-08 18:10 UTC, McBlankenburg commented on src/main/java/pl/simpleascoding/tutoringplatform/user/UserServiceImpl.java
> +import pl.simpleascoding.tutoringplatform.security.jwt.TokenRepository;
useless import

2023-07-08 18:10 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +import static org.mockito.BDDMockito.given;
useless import

2023-07-08 18:10 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +    PasswordEncoder passwordEncoder;
lack of import

2023-07-08 18:10 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +    JavaMailSender mailSender;
lack of import

2023-07-09 01:02 UTC, MateuszCiapala commented
In addition to that what @McBlankenburg said,
-remove unnecessary blank lines inside methods
-@DisplayName annotations should give short desc for eg. what method we're testing like: @DisplayName("confirmUserRegistration"), currently it's similar to the long method name which describes what it is testing already.)
-Consider extracting help methods like createUserEntity, createTokenEntity to helper class to avoid test classes being too long ( hundreds of lines of code for single test class may be considered as antypattern )

I'll review rest when it'll be finished and working (gh build has to pass)

2023-07-11 19:21 UTC, McBlankenburg requested changes

2023-07-11 19:21 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
//when

2023-07-11 19:21 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
>      }
I would add Mockito.verify() as static in short form just in case verify(), a method verifying whether tokenRepository was called once

2023-07-11 19:21 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
>          assertThat(resultRscpDTO, is(equalTo(expectedRscpDTO)));
I would add in //then Mockito.verify() as static in short form just in case verify(), a method verifying whether tokenRepository was called once

2023-07-11 19:21 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
>          RscpDTO<Object> expectedRscpDTO = new RscpDTO<>(RscpStatus.OK, "User registration confirmed.", null);
expectedRscpDTO should be in section //given

2023-07-11 19:21 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +    @DisplayName("confirmUserRegistration")
@DisplayName("should return expectedRscpDTO")  (i am not sure)

2023-07-11 21:06 UTC, MateuszCiapala commented
Branch is currently diverged with develop, it's required to be rebased. Consider of using "git reset --soft HEAD~X" where X is number of commits to be cancelled, your changes will be moved back to staging area and you'll be able to commit them again. This is one of the simplest option to fix your issue, then you'll just need to force push to rewrite your remote feature branch history.

2023-07-12 19:27 UTC, McBlankenburg requested changes

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +import static org.mockito.Mockito.*;
always use single imports for import reasons, you can set it in InteliJ to do it automatically

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
I recommend sticking to the Given When Then (BDD) convention

change Mockito.when() --> BDD Mockito given() (in //given section)
change Mockito.thenReturn() --> BDD Mockito .willReturn()
(of course without Mockito because we have static)

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        RscpDTO<?> resultRscpDTO = userServiceImpl.confirmUserRegistration(tokenEntity.getValue());
.confirmUserRegistration (we testing that method, so it should be in //when section)

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        verify(tokenRepository, atLeastOnce()).findTokenByValue(tokenEntity.getValue());
atLeastOnce()   so it will be fine when we refactor method and we call repository 10 000x ? Is there a justification?

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        //when
as above replace when() with given() and put it in //given section

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        verify(tokenRepository, atLeastOnce()).findTokenByValue(tokenEntity.getValue());
as above atLeastOnce() can i call it 10 000x ? Unit test it documentation for Software Developer, so when i read atLeastOnce it mean 1 or more.

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        //when
Mockito.when() --> BDDMockito.given() as above

when() --> given()

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        verify(tokenRepository, atLeastOnce()).findTokenByValue(tokenEntity.getValue());
verify should be in //then section

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        //when
as above

2023-07-12 19:27 UTC, McBlankenburg commented on src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java
> +        when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
as above

2023-07-13 17:34 UTC, dawciobiel approved these changes
LGTM,
next time please commit exactly only files that belong to this issue / pull-request

2023-07-13 17:35 UTC, sylvvester approved these changes
LGTM

2023-07-13 17:35 UTC, McBlankenburg approved these changes
good

2023-07-13 17:35 UTC, merged