new unit tests for TeacherService
Simple-as-Coding/tutoring-platform pull request #155
Opened 2023-07-18 16:34 UTC by GrzegorzHolui

2023-07-20 12:24 UTC, dawciobiel requested changes
Please fix the code formatting.

2023-07-20 12:24 UTC, dawciobiel commented on src/test/java/pl/simpleascoding/tutoringplatform/user/TeacherServiceImplTest.java
> +    private UserService userService;
```suggestion
    @InjectMocks
    private TeacherServiceImpl teacherService;
    
    @Mock
    private UserService userService;
```

2023-07-24 20:14 UTC, sylvvester requested changes

2023-07-24 20:14 UTC, sylvvester commented on src/test/java/pl/simpleascoding/tutoringplatform/user/TeacherServiceImplTest.java
> +        AssertionsForClassTypes.assertThat(thrown)
Unnecessary `AssertionsForClassTypes`; use `assertThat` directly.

2023-07-28 21:13 UTC, dawciobiel approved these changes
LGTM

2023-07-28 21:29 UTC, sylvvester approved these changes
LGTM

2023-07-28 21:31 UTC, merged